### ISSUE TITLE
Difficult naming methodology 

### ISSUE THREAD

**Issue by vapits** [CastleCSS/castlecss-boilerplate#5]
Hi there,

an other css framework is a step again in the future. I believe that is good to have as many options as we can and I thank you for your contribution here.

Though, I will not use this framework for now and my biggest issue is the naming of the classes.
It is probably a personal (or not) thing but I find very bad the naming of the classes. I would prefer something that tells me that it's framework's class first and secondary better explanatory about its functionality.

For example `m` is the class for default margin. One letter class is the definition of bad naming. This is happening also in most of naming on the classes and at least for my team this is not something useful. 

I wish you best of luck.

**Comment by dariusrosendahl** [comment]
Hi Vassilis,

Thank you for your opinion.

It's a shame that you think that CastleCSS wouldn't be a fit for you just because of our naming convention. We actually thought of what you suggest during our development process but using a class like ```castlecss-m``` just for margin was a bit too much.

Our train of thought is that easy and most used classes have a short, but readable name: ```m``` for margin, ```p``` for padding and ```ta-right``` to set a text-align right.

After that you can combine it with our grid system. So: ```m-b3``` gives you a margin from breakpoint 3 and up.

In essence we agree with you, but not for utility classes you use a *lot*.

**Comment by vapits** [comment]
By any means I'm not judging you guys. It's a "personal" question/statement just to leave it for consideration. Take care!
